version: '3'

services:
  wallace:
    image: node:latest
    container_name: wallace
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - '4000'
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: npm run dev --poll
    tty: true
    depends_on:
      - redisDB
    links:
      - redisDB
    networks:
      - production-network

  ## MONGO DB ##
  mongoDB:
    image: mongo
    container_name: mongoDB
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - production-network

  ## REDIS DB ###
  redisDB:
    image: redis:alpine
    container_name: redisDB
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
