version: '3.8'
services:
  nodeJs:
    image: node:latest
    container_name: nodeJs
    restart: always
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev

  db-mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017

  db-redis:
    image: redis:alpine
    container_name: redisDB
    restart: always
    depends_on:
      - nodeJS
    ports:
      - ${REDIS_PORT}:6379
